### ISSUE TITLE
Загрузка одного изображения дважды в Chrome невозможна

### ISSUE THREAD

**Issue by igordriagunov** [igordriagunov/bugs#1]
## Шаги по воспроизведению
1. Открыть в браузере Chrome сайт https://hackmd.io/
1. Выбрать: Use for free, создастся заметка
1. Выбрать пункт из верхнего меню "Загрузить изображение" (иконка камеры)
1. Выбрать изображение на своем компьютере и загрузить
1. Выбрать второй раз изображение из предыдущего пункта на своем компьютере и загрузить
**Ожидаемое поведение**: изображение загружено повторно
**Фактическое поведение**:  изображение не загружено

![screenshot 2018-11-05 20 22 34 jpg 1-2](https://user-images.githubusercontent.com/42145442/48015071-3b5aec00-e139-11e8-8a66-c5333603da59.jpg)
![screenshot 2018-11-05 20 25 19 jpg 3-4](https://user-images.githubusercontent.com/42145442/48015076-3dbd4600-e139-11e8-8406-9f617719e04c.jpg)
![screenshot 2018-11-05 20 28 41 jpg 5](https://user-images.githubusercontent.com/42145442/48015221-9db3ec80-e139-11e8-9bd3-83315385aadb.jpg)

## Входные данные
Windows 10
Chrome Версия 70.0.3538.77

gorod-ulica-noch-ogni.jpg
![gorod-ulica-noch-ogni](https://user-images.githubusercontent.com/42145442/48014426-b3281700-e137-11e8-9e12-a3c5c0e52b68.jpg)

**Comment by coursar** [comment]
@igoridze, необходимо указать:
1. Версию ОС
2. На каком конкретно шаге не совпало ожидаемое и фактическое поведение, а именно:
> Шаг 5. Загрузить повторно изображение
> **Ожидаемое поведение**: изображение загружено повторно
> **Фактическое поведение**: ...

**Comment by igordriagunov** [comment]
@coursar Дополнил

**Comment by coursar** [comment]
@igoridze, всё отлично. Из придирок четыре момента:
1. Название я бы дополнил до "В браузере Chrome в заметку невозможно добавить дважды одно и тоже изображение через функцию загрузки"
1. Нужно указывать разрядность ОС
1. Нужно проверить, всё ли ок в других браузерах, если в других - ок, то отразить этот факт в описании бага (например, в Firefox (ОС, версия) - загрузка работает)
1. На последней картинке (на которой и произошёл баг желательно отметить визуально, что картинка только одна)
