### ISSUE TITLE
Доступна загрузка изображения больше 5 Мб

### ISSUE THREAD

**Issue by igordriagunov** [igordriagunov/bugs#2]
###  Доступна загрузка изображения размером больше 5 Мб.

При загрузке изображения размера файла на сайте считается другим способом

### Шаги по воспроизведению

1. Открыть в браузере сайт https://tinypng.com
1. Скачать приложенный файл _2012-03-21_21-34-00-startrails.jpg_ на свой компьютер, проверить размер, перетянуть способом Drag&Drop на https://tinypng.com
1. Скачать приложенный файл _Snake_River.jpg_ на свой компьютер, проверить размер, перетянуть способом Drag&Drop на https://tinypng.com
**Ожидаемое поведение**: произойдет сжатие изображения
**Фактическое поведение**: файл больше 5 Мб, размер изображения не сжался

![screenshot 2018-11-08 21 26 15 jpg 5 2mb](https://user-images.githubusercontent.com/42145442/48300926-ae2be480-e4f6-11e8-9219-69a08219987e.jpg)

![screenshot 2018-11-10 14 25 47](https://user-images.githubusercontent.com/42145442/48436174-31676780-e78f-11e8-844e-deb556a75ecb.jpg)

### Входные данные

Windows 10, x64
Chrome Версия 70.0.3538.77

_Snake_River.jpg_
![snake_river_ 5mb](https://user-images.githubusercontent.com/42145442/48220246-de14a400-e39f-11e8-8d8a-cc93a58e1b4e.jpg)

_2012-03-21_21-34-00-startrails.jpg_
![2012-03-21_21-34-00-startrails](https://user-images.githubusercontent.com/42145442/48220257-e4a31b80-e39f-11e8-9bc8-b7ca63afb225.jpg)

**Comment by coursar** [comment]
@igoridze, вы в описание бага попытались вместить сразу два разных бага. Про первый (размер) - условно будем считать, что разработчик вам говорит: это не баг, мы считаем по формуле в 1 Кб - 1000 байт, поэтому всё корректно. По второму - файл больше 5 Мб действительно не должен загружаться.

**Comment by coursar** [comment]
@igoridze, а что если переформулировать так - баг в том, что при отображении размера файла он считается по одной формуле, а при расчёте ограничения (по размеру) по другой?

**Comment by coursar** [comment]
@igoridze, только не на компьютере, а на сайте. И непонятно, зачем вы выделяете размер, занимаемый на диске. В ожидаемое и фактическое поведение стоит включить главную функцию приложения - сжатие изображений. Работает ли оно?

**Comment by igordriagunov** [comment]
@coursar исправил описание, скрины, ожидаемое и фактическое

**Comment by coursar** [comment]
@igoridze, по факту, если считать по 1024, нельзя загрузить изображение больше 5мб, вы сами это показали в расчётах.

**Comment by igordriagunov** [comment]
@coursar т.е. вместо картинки 4,99 Мб нужна 5,00 Мб чтобы сжималась ?

**Comment by coursar** [comment]
Нет, суть бага в том, что отображаемый размер считается по одной формуле, а формула используемая для ограничения - другая.
